# Generated by Django 5.1.4 on 2025-01-14 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='masturbation',
            new_name='masturbation_time',
        ),
    ]
