# Generated by Django 5.1.4 on 2025-01-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_masturbation_user_masturbation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ejaculation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='masturbation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='porn_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
