# Generated by Django 5.1.4 on 2025-01-15 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_user_ejaculation_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ejaculation_target',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='user',
            name='masturbation',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='user',
            name='porn_targer',
            field=models.IntegerField(default=7),
        ),
    ]
