# Generated by Django 5.1.4 on 2025-01-15 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_ejaculation_target_user_masturbation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='masturbation',
            new_name='masturbation_target',
        ),
    ]
