# Generated by Django 5.1.4 on 2025-01-15 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_masturbation_user_masturbation_target'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='porn_targer',
            new_name='porn_target',
        ),
    ]
