# Generated by Django 5.1.4 on 2025-01-17 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_porn_targer_user_porn_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ejaculation_target',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='masturbation_target',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='porn_target',
            field=models.IntegerField(default=1),
        ),
    ]
