# Generated by Django 5.1.4 on 2025-01-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_user_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ejaculation_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='masturbation_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='porn_update',
            field=models.BooleanField(default=False),
        ),
    ]
